int getInt(int* input,char message[],char eMessage[], int lowLimit, int hiLimit);
int getFloat(float* input,char message[],char eMessage[], float lowLimit, float hiLimit);
int getChar(char* input,char message[],char eMessage[], char lowLimit, char hiLimit);
int getString(char* input,char message[],char eMessage[], int lowLimit, int hiLimit);
int esNumerico(char str[]);
int esSoloLetras(char str[]);
int esTelefono(char str[]);
int esAlfaNumerico(char str[]);
int esFloat(char str[]);
int getStringLetras(char mensaje[], char input[]);
int getStringNumeros(char mensaje[],char input[]);
int getStringFloat(char mensaje[], char input[]);
int getMail(char mensaje[], char input[]);
